language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - "pip install -r test_requirements.txt"
  - "pip install coveralls"

# command to run tests
script: 
  "coverage run --source lantern -m py.test"

after_success:
  coveralls
